version: '3.3'

services:
  db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todos
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
  app:
    image: "todoapp"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbinstance.cwesynuno7tj.us-east-2.rds.amazonaws.com:3306/todos
      SPRING_DATASOURCE_USERNAME: todo
      SPRING_DATASOURCE_PASSWORD: password
