version: '3.3'

services:
  db:
    image: "postgres:10.0-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: <password>
  app:
    image: "todoapp-java"
    deploy:
      replicas: 3
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: <password>
