version: '3.3'

services:
  db:
    image: "mysql:5.7.19"
    volumes:
      - data:/var/lib/mysql
    networks:
      backend:
        aliases:
          - mysql
          - db
    secrets:
      - source: db_password
        target: db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: todos
      MYSQL_USER: todo
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
  app:
    image: "todoapp"
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    secrets:
      - source: app_security
        target: security.properties

volumes:
  data:
    driver: local

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"

secrets:
  app_security:
    file: ./security.properties
  db_password:
    file: ./db_password
