spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
spring.mvc.static-path-pattern: /static/**
spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
